module.exports = {
    INVALID_ARGS: "Invalid command arguments provided!",
    NO_PERM: "You do not have permission to execute this command!",
    LOWER_ROLE: "The user you are trying to target has a higher role than you!",
    VALUE_NOT_SET: "No value provided! Skipping...",
    NO_ROLE: "No role found!",
    CONFIG_ERROR: "A configuration error has been discovered. Please contact a server administrator.",
    INVALID_MESSAGE: "Invalid message ID provided!",
    ALREADY_EXISTS: "This combination already exists!",
    BOT_PERM: "A bot permission error has occured",
    DOESNT_EXIST: "This combination does not exist!",
    EMOJI_NOT_FOUND: "This emoji cannot be found!",
    NO_LOCK: "No lockdown was found for this channel!",
    SET_LOCK: "A lockdown is already active for this channel!",
    NEED_VC: "A voice channel is required to play music!",
    NEED_VC_PERM: "I need the permissions to join and speak in your voice channel!",
    SONG_NOT_FOUND: "Song not found!",
    BAD_VAL: "Value provided was not a number or was too low!",
    TOO_HIGH: "The value provided is too high! Number must be between 1-10",
    ALR_RUN: "A setup has been detected as already running",
    NO_CAT: "No category was found under this name. Setup has been cancelled.",
    NO_R: "No role was found under this name. Setup has been cancelled.",
    NO_CH: "No channel was found under this name. Setup has been cancelled.",
    NO_T: "No ticket was found!",
    NO_EMB: "No embed is attached to this message!",
    LOWER_POS: "The role you are trying to target has a higher position than you!",
    ALR_R: "User already has this role!",
};